=== Arosmor/LMSGI_UD4/Clientes/Clientes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
        version="0.1" xml:lang="es">
    <xs:element name="clientes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="sede" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="direccion" type="xs:string"/>
                            <xs:element name="empleado" type="xs:string"/>
                            <xs:element name="fechaAlta" type="xs:string"/>
                            <xs:element name="descripcion" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="cliente" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="codigoCliente" type="xs:string"/>
                                                    <xs:element name="numero" type="xs:string"/>
                                                    <xs:element name="coste" type="xs:string"/>
                                                    <xs:element name="resumen" type="xs:string"/>
                                                    <xs:element name="plazo" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Arosmor/LMSGI_UD4/Clientes/Clientes_X.xml
<?xml version="1.0" encoding="UTF-8"?>
<clientes xmlns:xsi="http://www.w3.org/2001/XMLSchema/XMLschema-instance"
    xsi:noNamespaceSchemaLocation="Clientes.xsd">
    <sede codigo="E8778529">
        <direccion>calle alfonso III</direccion>
        <empleado>Pablo</empleado>
        <fechaAlta>22/07/2014</fechaAlta>
        <descripcion>solvente</descripcion>
        <cliente>
            <codigoCliente>EFT-654</codigoCliente>
            <numero>3</numero>
            <coste>5214€</coste>
            <Resumen>altas</Resumen>
            <plazo>34 dias</plazo>
        </cliente>
    </sede>
    <sede codigo="F5234098">
        <direccion>calle ronda</direccion>
        <empleado>Manuel</empleado>
        <fechaAlta>29/03/2007</fechaAlta>
        <descripcion>insolvente</descripcion>
        <cliente>
            <codigoCliente>WUL-576</codigoCliente>
            <numero>2</numero>
            <coste>8775€</coste>
            <Resumen>bajas</Resumen>
            <plazo>25 dias</plazo>
        </cliente>
    </sede>
</clientes>
